// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElAside: typeof import('element-plus/es')['ElAside'];
  const ElButton: typeof import('element-plus/es')['ElButton'];
  const ElCard: typeof import('element-plus/es')['ElCard'];
  const ElCol: typeof import('element-plus/es')['ElCol'];
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
  const ElContainer: typeof import('element-plus/es')['ElContainer'];
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker'];
  const ElDialog: typeof import('element-plus/es')['ElDialog'];
  const ElForm: typeof import('element-plus/es')['ElForm'];
  const ElFormItem: typeof import('element-plus/es')['ElFormItem'];
  const ElHeader: typeof import('element-plus/es')['ElHeader'];
  const ElIcon: typeof import('element-plus/es')['ElIcon'];
  const ElImage: typeof import('element-plus/es')['ElImage'];
  const ElInput: typeof import('element-plus/es')['ElInput'];
  const ElInputNumber: typeof import('element-plus/es')['ElInputNumber'];
  const ElMain: typeof import('element-plus/es')['ElMain'];
  const ElMenu: typeof import('element-plus/es')['ElMenu'];
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
  const ElMessage: typeof import('element-plus/es')['ElMessage'];
  const ElOption: typeof import('element-plus/es')['ElOption'];
  const ElPagination: typeof import('element-plus/es')['ElPagination'];
  const ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm'];
  const ElRadio: typeof import('element-plus/es')['ElRadio'];
  const ElRow: typeof import('element-plus/es')['ElRow'];
  const ElSelect: typeof import('element-plus/es')['ElSelect'];
  const ElStep: typeof import('element-plus/es')['ElStep'];
  const ElSteps: typeof import('element-plus/es')['ElSteps'];
  const ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
  const ElSwitch: typeof import('element-plus/es')['ElSwitch'];
  const ElTable: typeof import('element-plus/es')['ElTable'];
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
  const ElTimeline: typeof import('element-plus/es')['ElTimeline'];
  const ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem'];
  const ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect'];
  const ElUpload: typeof import('element-plus/es')['ElUpload'];
}
export {};
